# InventoryShare プラグイン設定ファイル

# このサーバーのID (任意のID)
server-id: "server1"

# データベース設定
database:
  host: "localhost"
  port: 3306
  name: "minecraft_inventory"
  user: "root"
  password: "password"
  useSSL: false

# 共有グループ設定
# 同じグループに属するサーバー間でインベントリが共有されます
sharing-groups:
  survival:
    - "server1"
    - "server2"
  creative:
    - "server3"
    - "server4"

# 各サーバーの設定
servers:
  server1:
    sync-enderchest: true
    sync-economy: true

  server2:
    sync-enderchest: true
    sync-economy: true

  server3:
    sync-enderchest: false
    sync-economy: true

  server4:
    sync-enderchest: true
    sync-economy: false
