# サーバーのID (任意のID)
server-id: "server1"

# データベース設定
database:
  type: mysql # または mariadb
  host: "localhost"
  port: 3306
  name: "minecraft_inventory"
  user: "root"
  password: "password"
  useSSL: false

# 共有グループ設定
# 同じグループに属するサーバー間でインベントリが共有される
sharing-groups:
  example1:
    - "server1"
    - "server2"
  example2:
    - "server1"
    - "server3"

# 各サーバーの設定
servers:
  server1:
    sync-enderchest: true
    sync-economy: true

  server2:
    sync-enderchest: true
    sync-economy: true

  server3:
    sync-enderchest: true
    sync-economy: true

sync:
  # 同期完了時のサウンド設定
  sync-completion-sound-enabled: true
  sync-completion-sound: "ENTITY_PLAYER_LEVELUP"
  sync-completion-sound-volume: 0.5
  sync-completion-sound-pitch: 1.0